version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # HTTP сервер
      - "8080:8080"  # WebSocket сервер
    environment:
      - NODE_ENV=production
      - EXPO_USE_FAST_RESOLVER=1
      - EXPO_NO_TELEMETRY=1
      - DATABASE_URL=postgresql://gen_user:Dima12211221@7f43f55089d91f30067cda7d.twc1.net:5432/default_db?sslmode=require
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.telegram-app.rule=Host(`your-domain.timeweb.ru`)"
      - "traefik.http.routers.telegram-app.tls=true"
      - "traefik.http.routers.telegram-app.tls.certresolver=letsencrypt"